puzzleslidegame: 
  #(rgb format python tuple) [red, green, blue] background color
  color_background: !!python/tuple [255,255,255]
  #(rgb format python tuple) [red, green, blue] color of menu elements
  color_lines: !!python/tuple [255,0,0]
  #(rgb format python tuple) [red, green, blue] color of some ui elements (those that are pngs blitet onto surfaces like home button or arrows)
  ui_elements_color: !!python/tuple [0,255,0]
  #(rgb format python tuple) [red, green, blue] color of the text
  text_color: !!python/tuple [0,255,255]
  #string name of font used in the game, pygame.font.get_fonts() for names of the system fonts
  font_name: "freesansbold"
  #languiage in info page and victory screen (0=pol, 1=eng)
  base_language: 0
difficulty_menu:
  #display difficulty menu if true
  is_difficulty_menu: true
  #easiest base_difficulty is 3 (3x3 board)
  base_difficulty: 3
tiles:
  #display id on top of tiles if true
  is_id_displayed: true
  #(rgb format python tuple) color of the id one the tiles
  id_display_color: !!python/tuple [0,255,255]
info_screen:
  #lines of text displayed on the info panel (string format)
  pol:
    - "Celem łamigłówki jest stworzenie obrazu poprzez ułożenie kafelków w odpowiedniej kolejności"
    - "Zmień stan planszy przesuwając kafelki w pustą przestrzeń układanki"
  eng:
    - "The goal of the puzzle is to complete the picture by rearranging tiles in a correct order"
    - "Change the state of the board by sliding tiles into an empty space"
victory_screen:
  #display text above the continue button if true
  is_victory_text_displayed: true
  #display text below the continue button if true
  is_continue_text_displayed: true
  #lines of text displayed on the victory panel (string format)
  pol:
  - "WYGRANA"
  - "Kliknij aby kontynuować"
  eng:
  - "VICTORY"
  - "Click to continue"